services:
  postgres:
    image: postgres:16.6
    container_name: throne-postgres
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=THRONEPWD
      - PGPORT=5435
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - throne-services
volumes:
  postgres-data:
networks:
  throne-services:
    driver: bridge
