POST http://localhost:8001/api/v1/integrations/6ba2371f-4774-4fc8-ae7e-7688db962b1a/mappings
Content-Type: application/json
x-throne-tenant: yeshua

{
  "type": "output",
  "sourceSchemaProps": {
    "name": "source schema",
    "schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "number"
        },
        "address": {
          "type": "object",
          "properties": {
            "street": {
              "type": "string"
            },
            "number": {
              "type": "number"
            }
          }
        }
      }
    }
  },
  "targetSchemaProps": {
    "name": "target schema",
    "schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "number"
        },
        "endereco": {
          "type": "object",
          "properties": {
            "rua": {
              "type": "string"
            },
            "numero": {
              "type": "number"
            }
          }
        }
      }
    }
  }
}

### Update Mapping
PUT http://localhost:8001/api/v1/integrations/6ba2371f-4774-4fc8-ae7e-7688db962b1a/mappings/60f88126-fbbb-44a4-9b70-a1a3fb4482bb
Content-Type: application/json
x-throne-tenant: yeshua

{

  "type": "input",
  "sourceSchemaProps": {
    "id": "f6bc37a5-c68d-467d-97e5-ee9cbaa681fd",
    "name": "source schema",
    "schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "number"
        }
      }
    }
  },
  "targetSchemaProps": {
    "id": "becc0667-a3d0-496b-9e9f-30db25e3d716",
    "name": "target schema",
    "schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "number"
        }
      }
    }
  }
}


### Update Mapping Template
PUT http://localhost:8001/api/v1/integrations/6ba2371f-4774-4fc8-ae7e-7688db962b1a/mappings/8a458d8d-8862-4ae1-97f8-014a78bd375a/template
Content-Type: application/json
x-throne-tenant: yeshua

{
  "mappingTemplate": {
    "name": {
      "type": "string",
      "sourcePath": ["name"]
    },
    "age": {
      "type": "number",
      "sourcePath": ["age"]
    },
    "endereco": {
      "type": "object",
      "sourcePath": ["endereco"],
      "properties": {
        "rua": {
          "type": "string",
          "sourcePath": ["endereco", "rua"]
        },
        "numero": {
          "type": "number",
          "sourcePath": ["endereco", "numero"]
        }
      }
    }
  }
}


### Delete Mapping
DELETE http://localhost:8001/api/v1/integrations/6ba2371f-4774-4fc8-ae7e-7688db962b1a/mappings/60f88126-fbbb-44a4-9b70-a1a3fb4482bb
Content-Type: application/json
x-throne-tenant: yeshua
