POST http://localhost:8001/api/v1/mappings/c6b75406-6eec-4603-bc8d-37c956e1b689
Content-Type: application/json
x-throne-tenant: yeshua

{
  "name": "test",
  "type": "input",
  "sourceSchemaProps": {
    "name": "source schema",
    "schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "number"
        }
      }
    }
  },
  "targetSchemaProps": {
    "name": "target schema",
    "schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "number"
        }
      }
    }
  }
}
