POST http://localhost:8001/api/v1/mappings/26843fdb-5a8b-42d0-8941-749a0d019ec5
Content-Type: application/json
x-throne-tenant: yeshua

{
  "name": "test",
  "type": "input",
  "sourceSchemaProps": {
    "name": "source schema",
    "schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "number"
        }
      }
    }
  },
  "targetSchemaProps": {
    "name": "target schema",
    "schema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "number"
        }
      }
    }
  }

}
